all:
  hosts:
    master-1:
      ansible_host: 192.168.50.101
      ip: 192.168.50.101
      access_ip: 192.168.50.101
    worker-1:
      ansible_host: 192.168.50.102
      ip: 192.168.50.102
      access_ip: 192.168.50.102
    worker-2:
      ansible_host: 192.168.50.103
      ip: 192.168.50.103
      access_ip: 192.168.50.103
  children:
    kube-master:
      hosts:
        master-1:
    kube-node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
